### PR TITLE
Update minecraft:icon for items

### PR DESCRIPTION
**Pull request by DinnerBeef**
This updates the minecraft:icon item component to be how minecraft does it. See [here](https://github.com/Mojang/bedrock-samples/blob/9fc3046e86a8316bfe71948652392433398c1334/behavior_pack/items/apple.json#L10)

Changed minecraft:icon from
 `"minecraft:icon": "$2.${3:${TM_FILENAME/[\\.].*//}}"`
 to 
`"minecraft:icon": {
              "texture": "$2.${3:${TM_FILENAME/[\\.].*//}}"
            }`

### CODE REVIEW

**Comment by DaanV2** [comment]
@DinnerBeef You update the auto-generated file 😬 

you want to look at: `source/behavior/items/format/components/icon.json`

**Comment by Xterionix** [comment]
Also incorrect, both formats are allowed

**Comment by DinnerBeef** [comment]
Will Fix :)

**Comment by DinnerBeef** [comment]
Ok think i did that right this time

**Comment by Xterionix** [comment]
That is the correct file but there's a reason that format isn't in the schemas. It's old. Used up to 1.20.50. The format changed after that. The schemas only contain the newest formats

**Comment by DinnerBeef** [comment]
I did not know that then. Will change how to do stuff then.

**Pull request closed without merging**
